import type { NextPage, GetStaticProps, GetStaticPaths } from "next";
import Head from "next/head";
import { Table } from "@components/Table";
import { BackButton } from "@components/buttons/BackButton";
import { dropColumnsByNames } from "@libs/tableUtils";
import { getTable, getTableFiles, TableInfoSet } from "@services/tables";

type PageProps = TableInfoSet;

type PathParams = {
  id: string;
};

export const getStaticPaths: GetStaticPaths<PathParams> = context => {
  const paths = getTableFiles().map(file => ({ params: { id: file } }));
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps<PageProps> = async context => {
  const { id } = context.params as PathParams;

  return {
    props: getTable(id),
  };
};

const TableOfId: NextPage<PageProps> = ({ table, tableInfo, attrInfo }: PageProps) => {
  const title = `表${tableInfo.number}. ${tableInfo.item}`;
  const [header, ...body] = dropColumnsByNames(table, ["id", "index", "H28ID"]);
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center p-2">
        <BackButton />
        <h1 className="m-4 text-xl font-bold">{title}</h1>
      </header>
      <div className="mx-4">
        <Table {...{ table, tableInfo, attrInfo }} />
      </div>
    </>
  );
};

export default TableOfId;
