import type { NextPage, GetStaticProps, GetStaticPaths } from "next";
import Head from "next/head";
import { Table } from "@components/Table";
import { BackButton } from "@components/buttons/BackButton";
import { dropColumnsByNames } from "@libs/tableUtils";
import { fmt } from "@libs/utils";
import { Locale, Locales, useLocaleText } from "@services/i18n/i18n";
import { getTable, getTableFiles, TableInfoSet } from "@services/tables";

type PageProps = TableInfoSet;

type PathParams = {
  id: string;
};

export const getStaticPaths: GetStaticPaths<PathParams> = () => {
  const paths = (["en", "ja"] as Locales)
    .map(locale => getTableFiles(locale as Locale).map(file => ({ params: { id: file }, locale })))
    .flat();
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps<PageProps> = async ({ locale, params }) => {
  const { id } = params as PathParams;

  return {
    props: getTable(id, locale as Locale),
  };
};

const TableOfId: NextPage<PageProps> = ({ table, tableInfo, attrInfo }: PageProps) => {
  const { t } = useLocaleText("@pages/list/table/[id]");
  const name = `${t("table") + tableInfo.number}. ${tableInfo.item}`;
  const [header, ...body] = dropColumnsByNames(table, ["id", "index", "H28ID"]);
  return (
    <>
      <Head>
        <title>{fmt(t("title"), { name })}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center p-2">
        <BackButton />
        <h1 className="m-4 text-xl font-bold">{name}</h1>
      </header>
      <div className="mx-4">
        <Table {...{ table, tableInfo, attrInfo }} />
      </div>
    </>
  );
};

export default TableOfId;
