import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import { OutcomesChecklists } from "@components/OutcomesChecklists";
import type { Tree } from "@libs/treeUtils";
import { Locale } from "@services/i18n/i18n";
import { loadFullOutcomesTable, makeOutcomesTree } from "@services/outcomes";
import type { OutcomeInfo } from "@services/outcomes";
import { loadTableInfoDict } from "@services/tables";

type PageProps = { outcomesTree: Tree<OutcomeInfo> };

export const getStaticProps: GetStaticProps<PageProps> = async ({ locale }) => {
  const table = loadFullOutcomesTable(locale as Locale);
  const tableInfoDict = loadTableInfoDict(locale as Locale);
  const outcomesTree = makeOutcomesTree(table, tableInfoDict, locale as Locale);

  return {
    props: { outcomesTree },
  };
};

const Home: NextPage<PageProps> = ({ outcomesTree }: PageProps) => {
  return (
    <>
      <Head>
        <title>Outcomes Checklists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <OutcomesChecklists outcomesTree={outcomesTree} />
    </>
  );
};

export default Home;
