import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import { MainLayout } from "@components/MainLayout";
import { OutcomesTree } from "@components/Outcomes";
import { OutcomesTOC } from "@components/OutcomesTOC";
import type { Tree } from "@libs/treeUtils";
import { loadFullOutcomesTable, makeOutcomesTree } from "@services/outcomes";
import type { OutcomeInfo } from "@services/outcomes";
import { loadTableInfoDict } from "@services/tables";

type PageProps = { outcomesTree: Tree<OutcomeInfo> };

export const getStaticProps: GetStaticProps<PageProps> = async (context) => {
  const table = loadFullOutcomesTable();
  const tableInfoDict = loadTableInfoDict();
  const outcomesTree = makeOutcomesTree(table, tableInfoDict);

  return {
    props: { outcomesTree },
  };
};

const Home: NextPage<PageProps> = ({ outcomesTree }: PageProps) => {
  return (
    <>
      <Head>
        <title>Core curriculum outcomes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout
        content={<OutcomesTree outcomesTree={outcomesTree} />}
        menu={<OutcomesTOC outcomesTree={outcomesTree} />}
      />
    </>
  );
};

export default Home;
