import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { ChangeEvent, useEffect, useState } from "react";
import { Table } from "@components/Table";
import { BackButton } from "@components/buttons/BackButton";
import { HeaderedTable } from "@libs/tableUtils";
import { Tree } from "@libs/treeUtils";
import { loadFullOutcomesTable, makeOutcomesTree } from "@services/outcomes";
import type { OutcomeInfo } from "@services/outcomes";
import { searchOutcomes, searchTables } from "@services/search";
import { getAllTables, loadTableInfoDict, TableInfo } from "@services/tables";

type PageProps = {
  outcomesTree: Tree<OutcomeInfo>;
  allTables: { table: HeaderedTable<string>; tableInfo: TableInfo }[];
};

export const getStaticProps: GetStaticProps<PageProps> = async (context) => {
  const table = loadFullOutcomesTable();
  const tableInfoDict = loadTableInfoDict();
  const outcomesTree = makeOutcomesTree(table, tableInfoDict);
  const allTables = getAllTables();

  return {
    props: { outcomesTree, allTables },
  };
};

const Breadcrumb = ({ parents }: { parents: OutcomeInfo[] }) => {
  return (
    <>
      {parents.map((parent, i) => {
        return (
          <span className="text-xs text-gray-400" key={parent.id}>
            {i !== 0 ? ` / ` : ""}
            <span>
              {parent.index.slice(-2)}
              {parent.text}
            </span>
          </span>
        );
      })}
    </>
  );
};

const SearchBar = ({
  value,
  onChange,
}: {
  value: string;
  onChange: (e: ChangeEvent<HTMLInputElement>) => void;
}) => {
  return (
    <div className="sticky top-0 flex w-full items-center bg-white/80 backdrop-blur-sm">
      <div className="ml-2">
        <BackButton />
      </div>
      <input
        type="text"
        className="input-bordered input m-4 w-full max-w-xs"
        placeholder="検索語もしくはカンマ区切りid"
        value={value}
        onChange={(e) => onChange(e)}
      />
    </div>
  );
};

const SearchPage: NextPage<PageProps> = ({ outcomesTree, allTables }: PageProps) => {
  const router = useRouter();
  const [searchText, setSearchText] = useState("");
  useEffect(() => {
    const { q } = router.query;
    if (q) setSearchText(q as string);
  }, [router]);
  return (
    <>
      <Head>
        <title>Search Core curriculum outcomes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="ml-4">
        <SearchBar value={searchText} onChange={(e) => setSearchText(e.target.value)} />
        <div>
          {searchOutcomes(outcomesTree, searchText).map((item) => (
            <div className="m-4" key={item.id}>
              <div>
                <span className="mr-2 font-light text-sky-600">{item.index}</span>
                {item.text}
                <span className="ml-2 font-light text-sky-600">{item.id}</span>
              </div>
              <Breadcrumb parents={item.parents} />
            </div>
          ))}
        </div>
        <div>
          {searchTables(searchText, allTables).map(({ table, tableInfo }) => {
            const title = `表${tableInfo.index}. ${tableInfo.item}`;

            return (
              <div key={tableInfo.id}>
                <Link href={tableInfo.link} passHref>
                  <div>
                    <div className="my-4">{title}</div>
                    <Table table={table as HeaderedTable<string>} tableInfo={tableInfo} />
                  </div>
                </Link>
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
};

export default SearchPage;
